import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  languageSidebar: [{type: 'autogenerated', dirName: 'language'}],
  //realizerSidebar: [{type: 'autogenerated', dirName: 'realizer'}],
};

export default sidebars;
