import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mainSidebar: [{type: 'autogenerated', dirName: './'}],
  //realizerSidebar: [{type: 'autogenerated', dirName: 'realizer'}],
};

export default sidebars;
